typedef struct{
    int day;
    int month;
    int year;
    int hour;
    int minute;
} datatime;

datatime *construct(int day, int month, int year, int hour, int minute);
datatime *construct_default();
datatime *construct_copy(datatime dt);
void destroy(datatime* dt);
int is_leap_year(int year);
long get_timestamp(datatime dt);
datatime *create_datatime_from_timestamp(long timestamp);
void print_day(datatime dt);
void print_hour(datatime dt);
void print_year(datatime dt);
void print_month(datatime dt);
void print_minute(datatime dt);
void fprint_date(datatime dt);
void print_date(datatime dt);
void set_day(datatime *dt, int day);
void set_month(datatime *dt, int month);
void set_minute(datatime *dt, int minute);
void set_hour(datatime *dt, int hour);
void set_year(datatime *dt, int year);
void enter_date(datatime *dt);
void fenter_date(datatime *dt);
int greater(datatime dt1, datatime dt2);
int less(datatime dt1, datatime dt2);
int greater_loosely(datatime dt1, datatime dt2);
int less_loosely(datatime dt1, datatime dt2);
int equals(datatime dt1, datatime dt2);
int not_equals(datatime dt1, datatime dt2);
datatime *get_time_difference(datatime dt1, datatime dt2);
int get_time_difference_minutes(datatime dt1, datatime dt2);
int get_time_difference_hours(datatime dt1, datatime dt2);
int get_time_difference_days(datatime dt1, datatime dt2);
int get_time_difference_years(datatime dt1, datatime dt2);
int get_time_difference_months(datatime dt1, datatime dt2);
